# Generated by Django 3.0 on 2022-09-05 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NoteTake', '0003_user_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='userid',
            field=models.CharField(default=-1, max_length=1000),
            preserve_default=False,
        ),
    ]
